# These are supported funding model platforms

github: [rjdj0261] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: rjdj0261 # Replace with a single Patreon username
custom: ['https://paypal.me/rjdj0261?country.x=IN&locale.x=en_GB'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
