# These are supported funding model platforms

patreon: rjdj0261 # Replace with a single Patreon username
custom: ['https://paypal.me/rjdj0261'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
